version: '3'

services:
  payment:
    build: ./
    depends_on:
      - 'database'
    ports: 
      - '3003:3003'

  description:
    build: ./description
    depends_on:
      - 'database'
    ports:
      - '3001:3001'

  feedback:
    build: ./feedback
    depends_on:
      - 'database'
    ports: 
      - '3002:3002'

  database:
    image: mongo:latest
